<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function comment_registration_email_form_node_type_form_alter(&$form, $form_state) {
  if (isset($form['type'])) {

    // Hide Username
    $form['comment_registration']['comment_registration_container']['comment_registration_email_hide_username'] = array(
      '#title' => 'Email registration',
      '#description' => t('Hide core comment Author field and auto generate username from email.'),
      '#type' => 'checkbox',
      '#default_value' => variable_get('comment_registration_email_hide_username_' . $form['#node_type']->type, 0),
      '#weight' => 2,
    );   
  }
  //dpm($form);
}