<?php

// ADMIN

/**
 * Implements hook_form_FORM_ID_alter().
 */
function comment_registration_profile2_form_node_type_form_alter(&$form, $form_state) {
  if (isset($form['type'])) {

    $profile_types = profile2_get_types();
    if ($profile_types) {    
      // Container
      $form['comment_registration']['comment_registration_profile2_container'] = array(
        '#type' => 'container',
        '#states' => array(
          'visible' => array(
            array(':input[name="comment_registration_enabled"]' => array('checked' => TRUE)),       
          ),
        ),
      );
      // Profile 2 radios
      $options = array('_none' => "None");
      foreach ($profile_types as $type_name => $profile_type) {
        $options[$profile_type->type] = $profile_type->label;
      }
      $form['comment_registration']['comment_registration_profile2_container']['comment_registration_profile2_type'] = array(
        '#type' => 'radios',
        '#title' => t('Comment Registration Profile'),
        '#default_value' => variable_get('comment_registration_profile2_type_' . $form['#node_type']->type, array()),
        '#description' => t('The profile2 to include in comment registrations for this content type.'),
        '#options' => $options,
        '#weight' => 1,
      );
    }
    system_settings_form($form);
  }
}

// USER FORM

function comment_registration_profile2_form_comment_form_alter(&$form, &$form_state, $form_id) {

  // Config variables
  $type_name = variable_get('comment_registration_profile2_type_' . $form['#node']->type, array());

  // Include profile2 on comment registration form
  if (!empty($type_name) && $type_name != '_none') {
    if (empty($form_state['profiles'][$type_name])) {
      $form_state['profiles'][$type_name] = profile2_create(array('type' => $type_name));
    }
    profile2_attach_form($form, $form_state);
  }
  $form['profile_' . $type_name]['#states'] = array(
    'visible' => array(
      array(':input[name="comment_registration_register"]' => array('checked' => TRUE)),       
    ),
  );

  // Wrap profile2 inside in a fieldset.
  $form['profile_' . $type_name] += array(
    '#type' => 'fieldset', 
    '#states' => array(
      'visible' => array(
        array(':input[name="comment_registration_register"]' => array('checked' => TRUE)),       
      ),
    ),
  );
}