<?php

// ADMIN

/**
 * Implements hook_form_FORM_ID_alter().
 */
//function comment_registration_email_form_node_type_form_alter(&$form, $form_state) {
//  if (isset($form['type'])) {
//
//    // Hide Username
//    $form['comment_registration']['comment_registration_container']['comment_registration_email_hide_username'] = //array(
//      '#title' => 'Email registration',
//      '#description' => t('Hide core comment Author field and auto generate username from email.'),
//      '#type' => 'checkbox',
//      '#default_value' => variable_get('comment_registration_email_hide_username_' . $form['#node_type']->type, 0),
//      '#weight' => 2,
//    );   
//  }
//  //dpm($form);
//}

// FRONT END

///**
// * Submit handler for comment registration form.
// */
//function comment_registration_email_submit($form, &$form_state) {
//  if ($form_state['values']['comment_registration_register'] == 1) {
//
//    // Config variables
//    $hide_username = variable_get('comment_registration_hide_username_' . $form['#node']->type, array());
//
//    if ($hide_username) {
//      //$form['author']['name']['#required'] = FALSE;
//      //hide($form['author']['name']);
//      array_unshift($form['#validate'], 'comment_registration_profile2_form_comment_form_validate');
//    }
//
//    // setup the user registration form and submit via the user registration submit function
//    $form['comment_registration_form']['form']['account']['name'] = $form_state['values']['name'];//